//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 03:57:35 PM CEST 
//


package iof.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * &lt;p&gt;Java class for ResultStatus.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * &lt;pre&gt;
 * &amp;lt;simpleType name="ResultStatus"&amp;gt;
 *   &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&amp;gt;
 *     &amp;lt;enumeration value="OK"/&amp;gt;
 *     &amp;lt;enumeration value="Finished"/&amp;gt;
 *     &amp;lt;enumeration value="MissingPunch"/&amp;gt;
 *     &amp;lt;enumeration value="Disqualified"/&amp;gt;
 *     &amp;lt;enumeration value="DidNotFinish"/&amp;gt;
 *     &amp;lt;enumeration value="Active"/&amp;gt;
 *     &amp;lt;enumeration value="Inactive"/&amp;gt;
 *     &amp;lt;enumeration value="OverTime"/&amp;gt;
 *     &amp;lt;enumeration value="SportingWithdrawal"/&amp;gt;
 *     &amp;lt;enumeration value="NotCompeting"/&amp;gt;
 *     &amp;lt;enumeration value="Moved"/&amp;gt;
 *     &amp;lt;enumeration value="MovedUp"/&amp;gt;
 *     &amp;lt;enumeration value="DidNotStart"/&amp;gt;
 *     &amp;lt;enumeration value="DidNotEnter"/&amp;gt;
 *     &amp;lt;enumeration value="Cancelled"/&amp;gt;
 *   &amp;lt;/restriction&amp;gt;
 * &amp;lt;/simpleType&amp;gt;
 * &lt;/pre&gt;
 * 
 */
@XmlType(name = "ResultStatus")
@XmlEnum
public enum ResultStatus {


    /**
     * 
     *             Finished and validated.
     *           
     * 
     */
    OK("OK"),

    /**
     * 
     *             Finished but not yet validated.
     *           
     * 
     */
    @XmlEnumValue("Finished")
    FINISHED("Finished"),

    /**
     * 
     *             Missing punch.
     *           
     * 
     */
    @XmlEnumValue("MissingPunch")
    MISSING_PUNCH("MissingPunch"),

    /**
     * 
     *             Disqualified (for some other reason than a missing punch).
     *           
     * 
     */
    @XmlEnumValue("Disqualified")
    DISQUALIFIED("Disqualified"),

    /**
     * 
     *             Did not finish (i.e. conciously cancelling the race after having started, in contrast to MissingPunch).
     *           
     * 
     */
    @XmlEnumValue("DidNotFinish")
    DID_NOT_FINISH("DidNotFinish"),

    /**
     * 
     *             Currently on course.
     *           
     * 
     */
    @XmlEnumValue("Active")
    ACTIVE("Active"),

    /**
     * 
     *             Has not yet started.
     *           
     * 
     */
    @XmlEnumValue("Inactive")
    INACTIVE("Inactive"),

    /**
     * 
     *             Overtime, i.e. did not finish within the maximum time set by the organiser.
     *           
     * 
     */
    @XmlEnumValue("OverTime")
    OVER_TIME("OverTime"),

    /**
     * 
     *             Sporting withdrawal (e.g. helping an injured competitor).
     *           
     * 
     */
    @XmlEnumValue("SportingWithdrawal")
    SPORTING_WITHDRAWAL("SportingWithdrawal"),

    /**
     * 
     *             Not competing (i.e. running outside the competition).
     *           
     * 
     */
    @XmlEnumValue("NotCompeting")
    NOT_COMPETING("NotCompeting"),

    /**
     * 
     *             Moved to another class.
     *           
     * 
     */
    @XmlEnumValue("Moved")
    MOVED("Moved"),

    /**
     * 
     *             Moved to a "better" class, in case of entry restrictions.
     *           
     * 
     */
    @XmlEnumValue("MovedUp")
    MOVED_UP("MovedUp"),

    /**
     * 
     *             Did not start (in this race).
     *           
     * 
     */
    @XmlEnumValue("DidNotStart")
    DID_NOT_START("DidNotStart"),

    /**
     * 
     *             Did not enter (in this race).
     *           
     * 
     */
    @XmlEnumValue("DidNotEnter")
    DID_NOT_ENTER("DidNotEnter"),

    /**
     * 
     *             The competitor has cancelled his/hers entry.
     *           
     * 
     */
    @XmlEnumValue("Cancelled")
    CANCELLED("Cancelled");
    private final String value;

    ResultStatus(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResultStatus fromValue(String v) {
        for (ResultStatus c: ResultStatus.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
