//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 03:57:34 PM CEST 
//


package iof.v2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element ref="{}EntryId" minOccurs="0"/&amp;gt;
 *         &amp;lt;choice&amp;gt;
 *           &amp;lt;sequence&amp;gt;
 *             &amp;lt;choice&amp;gt;
 *               &amp;lt;element ref="{}PersonId"/&amp;gt;
 *               &amp;lt;element ref="{}Person"/&amp;gt;
 *             &amp;lt;/choice&amp;gt;
 *             &amp;lt;element ref="{}CCard" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *             &amp;lt;element ref="{}Rank" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *           &amp;lt;/sequence&amp;gt;
 *           &amp;lt;sequence&amp;gt;
 *             &amp;lt;element ref="{}TeamName"/&amp;gt;
 *             &amp;lt;sequence maxOccurs="unbounded" minOccurs="0"&amp;gt;
 *               &amp;lt;choice minOccurs="0"&amp;gt;
 *                 &amp;lt;element ref="{}ClubId"/&amp;gt;
 *                 &amp;lt;element ref="{}Club"/&amp;gt;
 *               &amp;lt;/choice&amp;gt;
 *               &amp;lt;element ref="{}TeamSequence" minOccurs="0"/&amp;gt;
 *             &amp;lt;/sequence&amp;gt;
 *           &amp;lt;/sequence&amp;gt;
 *         &amp;lt;/choice&amp;gt;
 *         &amp;lt;element ref="{}EntryClass" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}AllocationControl" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}EntryDate"/&amp;gt;
 *         &amp;lt;element ref="{}ModifyDate" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="nonCompetitor" default="N"&amp;gt;
 *         &amp;lt;simpleType&amp;gt;
 *           &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&amp;gt;
 *             &amp;lt;enumeration value="Y"/&amp;gt;
 *             &amp;lt;enumeration value="N"/&amp;gt;
 *           &amp;lt;/restriction&amp;gt;
 *         &amp;lt;/simpleType&amp;gt;
 *       &amp;lt;/attribute&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entryId",
    "personId",
    "person",
    "cCard",
    "rank",
    "teamName",
    "clubIdOrClubAndTeamSequence",
    "entryClass",
    "allocationControl",
    "entryDate",
    "modifyDate"
})
@XmlRootElement(name = "Entry")
public class Entry {

    @XmlElement(name = "EntryId")
    protected String entryId;
    @XmlElement(name = "PersonId")
    protected PersonId personId;
    @XmlElement(name = "Person")
    protected Person person;
    @XmlElement(name = "CCard")
    protected List<CCard> cCard;
    @XmlElement(name = "Rank")
    protected List<Rank> rank;
    @XmlElement(name = "TeamName")
    protected String teamName;
    @XmlElements({
        @XmlElement(name = "ClubId", type = ClubId.class),
        @XmlElement(name = "Club", type = Club.class),
        @XmlElement(name = "TeamSequence", type = String.class)
    })
    protected List<Object> clubIdOrClubAndTeamSequence;
    @XmlElement(name = "EntryClass")
    protected List<EntryClass> entryClass;
    @XmlElement(name = "AllocationControl")
    protected AllocationControl allocationControl;
    @XmlElement(name = "EntryDate", required = true)
    protected EntryDate entryDate;
    @XmlElement(name = "ModifyDate")
    protected ModifyDate modifyDate;
    @XmlAttribute(name = "nonCompetitor")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String nonCompetitor;

    /**
     * Gets the value of the entryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryId() {
        return entryId;
    }

    /**
     * Sets the value of the entryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryId(String value) {
        this.entryId = value;
    }

    /**
     * Gets the value of the personId property.
     * 
     * @return
     *     possible object is
     *     {@link PersonId }
     *     
     */
    public PersonId getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonId }
     *     
     */
    public void setPersonId(PersonId value) {
        this.personId = value;
    }

    /**
     * Gets the value of the person property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getPerson() {
        return person;
    }

    /**
     * Sets the value of the person property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setPerson(Person value) {
        this.person = value;
    }

    /**
     * Gets the value of the cCard property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the cCard property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getCCard().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link CCard }
     * 
     * 
     */
    public List<CCard> getCCard() {
        if (cCard == null) {
            cCard = new ArrayList<CCard>();
        }
        return this.cCard;
    }

    /**
     * Gets the value of the rank property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the rank property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getRank().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Rank }
     * 
     * 
     */
    public List<Rank> getRank() {
        if (rank == null) {
            rank = new ArrayList<Rank>();
        }
        return this.rank;
    }

    /**
     * Gets the value of the teamName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * Sets the value of the teamName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeamName(String value) {
        this.teamName = value;
    }

    /**
     * Gets the value of the clubIdOrClubAndTeamSequence property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the clubIdOrClubAndTeamSequence property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getClubIdOrClubAndTeamSequence().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link ClubId }
     * {@link Club }
     * {@link String }
     * 
     * 
     */
    public List<Object> getClubIdOrClubAndTeamSequence() {
        if (clubIdOrClubAndTeamSequence == null) {
            clubIdOrClubAndTeamSequence = new ArrayList<Object>();
        }
        return this.clubIdOrClubAndTeamSequence;
    }

    /**
     * Gets the value of the entryClass property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the entryClass property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getEntryClass().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link EntryClass }
     * 
     * 
     */
    public List<EntryClass> getEntryClass() {
        if (entryClass == null) {
            entryClass = new ArrayList<EntryClass>();
        }
        return this.entryClass;
    }

    /**
     * Gets the value of the allocationControl property.
     * 
     * @return
     *     possible object is
     *     {@link AllocationControl }
     *     
     */
    public AllocationControl getAllocationControl() {
        return allocationControl;
    }

    /**
     * Sets the value of the allocationControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link AllocationControl }
     *     
     */
    public void setAllocationControl(AllocationControl value) {
        this.allocationControl = value;
    }

    /**
     * Gets the value of the entryDate property.
     * 
     * @return
     *     possible object is
     *     {@link EntryDate }
     *     
     */
    public EntryDate getEntryDate() {
        return entryDate;
    }

    /**
     * Sets the value of the entryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryDate }
     *     
     */
    public void setEntryDate(EntryDate value) {
        this.entryDate = value;
    }

    /**
     * Gets the value of the modifyDate property.
     * 
     * @return
     *     possible object is
     *     {@link ModifyDate }
     *     
     */
    public ModifyDate getModifyDate() {
        return modifyDate;
    }

    /**
     * Sets the value of the modifyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifyDate }
     *     
     */
    public void setModifyDate(ModifyDate value) {
        this.modifyDate = value;
    }

    /**
     * Gets the value of the nonCompetitor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNonCompetitor() {
        if (nonCompetitor == null) {
            return "N";
        } else {
            return nonCompetitor;
        }
    }

    /**
     * Sets the value of the nonCompetitor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNonCompetitor(String value) {
        this.nonCompetitor = value;
    }

}
