//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.10 at 03:57:34 PM CEST 
//


package iof.v2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * &lt;p&gt;Java class for anonymous complex type.
 * 
 * &lt;p&gt;The following schema fragment specifies the expected content contained within this class.
 * 
 * &lt;pre&gt;
 * &amp;lt;complexType&amp;gt;
 *   &amp;lt;complexContent&amp;gt;
 *     &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&amp;gt;
 *       &amp;lt;sequence&amp;gt;
 *         &amp;lt;element ref="{}EventId"/&amp;gt;
 *         &amp;lt;element ref="{}Name"/&amp;gt;
 *         &amp;lt;choice&amp;gt;
 *           &amp;lt;element ref="{}EventClassificationId"/&amp;gt;
 *           &amp;lt;element ref="{}EventClassification"/&amp;gt;
 *         &amp;lt;/choice&amp;gt;
 *         &amp;lt;element ref="{}StartDate"/&amp;gt;
 *         &amp;lt;element ref="{}FinishDate" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}EventOfficial" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}Organiser" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}EventClass" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}EventRace" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}WebURL" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}EntryData" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}Service" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}Account" maxOccurs="unbounded" minOccurs="0"/&amp;gt;
 *         &amp;lt;element ref="{}ModifyDate" minOccurs="0"/&amp;gt;
 *       &amp;lt;/sequence&amp;gt;
 *       &amp;lt;attribute name="eventForm" default="IndSingleDay"&amp;gt;
 *         &amp;lt;simpleType&amp;gt;
 *           &amp;lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&amp;gt;
 *             &amp;lt;enumeration value="IndSingleDay"/&amp;gt;
 *             &amp;lt;enumeration value="IndMultiDay"/&amp;gt;
 *             &amp;lt;enumeration value="teamSingleDay"/&amp;gt;
 *             &amp;lt;enumeration value="teamMultiDay"/&amp;gt;
 *             &amp;lt;enumeration value="relay"/&amp;gt;
 *           &amp;lt;/restriction&amp;gt;
 *         &amp;lt;/simpleType&amp;gt;
 *       &amp;lt;/attribute&amp;gt;
 *     &amp;lt;/restriction&amp;gt;
 *   &amp;lt;/complexContent&amp;gt;
 * &amp;lt;/complexType&amp;gt;
 * &lt;/pre&gt;
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eventId",
    "name",
    "eventClassificationId",
    "eventClassification",
    "startDate",
    "finishDate",
    "eventOfficial",
    "organiser",
    "eventClass",
    "eventRace",
    "webURL",
    "entryData",
    "service",
    "account",
    "modifyDate"
})
@XmlRootElement(name = "Event")
public class Event {

    @XmlElement(name = "EventId", required = true)
    protected EventId eventId;
    @XmlElement(name = "Name", required = true)
    protected Name name;
    @XmlElement(name = "EventClassificationId")
    protected EventClassificationId eventClassificationId;
    @XmlElement(name = "EventClassification")
    protected EventClassification eventClassification;
    @XmlElement(name = "StartDate", required = true)
    protected StartDate startDate;
    @XmlElement(name = "FinishDate")
    protected FinishDate finishDate;
    @XmlElement(name = "EventOfficial")
    protected List<EventOfficial> eventOfficial;
    @XmlElement(name = "Organiser")
    protected Organiser organiser;
    @XmlElement(name = "EventClass")
    protected List<EventClass> eventClass;
    @XmlElement(name = "EventRace")
    protected List<EventRace> eventRace;
    @XmlElement(name = "WebURL")
    protected List<String> webURL;
    @XmlElement(name = "EntryData")
    protected EntryData entryData;
    @XmlElement(name = "Service")
    protected List<Service> service;
    @XmlElement(name = "Account")
    protected List<Account> account;
    @XmlElement(name = "ModifyDate")
    protected ModifyDate modifyDate;
    @XmlAttribute(name = "eventForm")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String eventForm;

    /**
     * Gets the value of the eventId property.
     * 
     * @return
     *     possible object is
     *     {@link EventId }
     *     
     */
    public EventId getEventId() {
        return eventId;
    }

    /**
     * Sets the value of the eventId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventId }
     *     
     */
    public void setEventId(EventId value) {
        this.eventId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link Name }
     *     
     */
    public Name getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link Name }
     *     
     */
    public void setName(Name value) {
        this.name = value;
    }

    /**
     * Gets the value of the eventClassificationId property.
     * 
     * @return
     *     possible object is
     *     {@link EventClassificationId }
     *     
     */
    public EventClassificationId getEventClassificationId() {
        return eventClassificationId;
    }

    /**
     * Sets the value of the eventClassificationId property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventClassificationId }
     *     
     */
    public void setEventClassificationId(EventClassificationId value) {
        this.eventClassificationId = value;
    }

    /**
     * Gets the value of the eventClassification property.
     * 
     * @return
     *     possible object is
     *     {@link EventClassification }
     *     
     */
    public EventClassification getEventClassification() {
        return eventClassification;
    }

    /**
     * Sets the value of the eventClassification property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventClassification }
     *     
     */
    public void setEventClassification(EventClassification value) {
        this.eventClassification = value;
    }

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link StartDate }
     *     
     */
    public StartDate getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartDate }
     *     
     */
    public void setStartDate(StartDate value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the finishDate property.
     * 
     * @return
     *     possible object is
     *     {@link FinishDate }
     *     
     */
    public FinishDate getFinishDate() {
        return finishDate;
    }

    /**
     * Sets the value of the finishDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link FinishDate }
     *     
     */
    public void setFinishDate(FinishDate value) {
        this.finishDate = value;
    }

    /**
     * Gets the value of the eventOfficial property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the eventOfficial property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getEventOfficial().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link EventOfficial }
     * 
     * 
     */
    public List<EventOfficial> getEventOfficial() {
        if (eventOfficial == null) {
            eventOfficial = new ArrayList<EventOfficial>();
        }
        return this.eventOfficial;
    }

    /**
     * Gets the value of the organiser property.
     * 
     * @return
     *     possible object is
     *     {@link Organiser }
     *     
     */
    public Organiser getOrganiser() {
        return organiser;
    }

    /**
     * Sets the value of the organiser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Organiser }
     *     
     */
    public void setOrganiser(Organiser value) {
        this.organiser = value;
    }

    /**
     * Gets the value of the eventClass property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the eventClass property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getEventClass().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link EventClass }
     * 
     * 
     */
    public List<EventClass> getEventClass() {
        if (eventClass == null) {
            eventClass = new ArrayList<EventClass>();
        }
        return this.eventClass;
    }

    /**
     * Gets the value of the eventRace property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the eventRace property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getEventRace().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link EventRace }
     * 
     * 
     */
    public List<EventRace> getEventRace() {
        if (eventRace == null) {
            eventRace = new ArrayList<EventRace>();
        }
        return this.eventRace;
    }

    /**
     * Gets the value of the webURL property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the webURL property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getWebURL().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getWebURL() {
        if (webURL == null) {
            webURL = new ArrayList<String>();
        }
        return this.webURL;
    }

    /**
     * Gets the value of the entryData property.
     * 
     * @return
     *     possible object is
     *     {@link EntryData }
     *     
     */
    public EntryData getEntryData() {
        return entryData;
    }

    /**
     * Sets the value of the entryData property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntryData }
     *     
     */
    public void setEntryData(EntryData value) {
        this.entryData = value;
    }

    /**
     * Gets the value of the service property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the service property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getService().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Service }
     * 
     * 
     */
    public List<Service> getService() {
        if (service == null) {
            service = new ArrayList<Service>();
        }
        return this.service;
    }

    /**
     * Gets the value of the account property.
     * 
     * &lt;p&gt;
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a &lt;CODE&gt;set&lt;/CODE&gt; method for the account property.
     * 
     * &lt;p&gt;
     * For example, to add a new item, do as follows:
     * &lt;pre&gt;
     *    getAccount().add(newItem);
     * &lt;/pre&gt;
     * 
     * 
     * &lt;p&gt;
     * Objects of the following type(s) are allowed in the list
     * {@link Account }
     * 
     * 
     */
    public List<Account> getAccount() {
        if (account == null) {
            account = new ArrayList<Account>();
        }
        return this.account;
    }

    /**
     * Gets the value of the modifyDate property.
     * 
     * @return
     *     possible object is
     *     {@link ModifyDate }
     *     
     */
    public ModifyDate getModifyDate() {
        return modifyDate;
    }

    /**
     * Sets the value of the modifyDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ModifyDate }
     *     
     */
    public void setModifyDate(ModifyDate value) {
        this.modifyDate = value;
    }

    /**
     * Gets the value of the eventForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventForm() {
        if (eventForm == null) {
            return "IndSingleDay";
        } else {
            return eventForm;
        }
    }

    /**
     * Sets the value of the eventForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventForm(String value) {
        this.eventForm = value;
    }

}
