//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.3 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.27 at 08:36:50 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.orienteering.org/datastandard/3.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package v3;
